myPro/Models/PV.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace myPro.Models
{
	public class PV
	{
		public string Text { get; set; }
	}

	//public string Text="";
}

myPro/Controllers/ABController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace myPro.Controllers
{
    public class ABController : Controller
    {
        public ActionResult PV()
		{
			ViewBag.part = "Part";
			return PartialView();
		}
    }
}

myPro/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;

namespace myPro.Controllers
{
	public class HomeController : Controller
	{
		public ActionResult Index()
		{
			var mvcName = typeof(Controller).Assembly.GetName();
			var isMono = Type.GetType("Mono.Runtime") != null;

			ViewData["Version"] = mvcName.Version.Major + "." + mvcName.Version.Minor;
			ViewData["Runtime"] = isMono ? "Mono" : ".NET";

			return View();
		}
	}
}

myPro/Controllers/PVController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace myPro.Controllers
{
    public class PVController : Controller
    {
        public class MyModel
	{
		public int Prop1 { get; set; }
		public int Prop2 { get; set; }
	}

        public PartialViewResult PV()
	{
		TempData["Hello"] = "Hello from PartController";
		return PartialView();

	}

	public PartialViewResult MenuView()
	{
		var data = new MyModel() { Prop1 = 5, Prop2 = 10 };
		return PartialView("~/Views/Shared/PV.cshtml", data);
	}

	/*public ViewResult VR(int ID)
	{
		int idd = ID + 10;
		return View(idd);
	}*/
    }
}

myPro/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace myPro.Controllers
{
    public class TestController : Controller
    {
        public ActionResult Index()
        {
			ViewBag.test = "Testing...";
			ViewBag.title = "Test Title";
            return View();
        }
    }
}

myPro/Views/Home/Index.cshtml
<h2>Welcome to ASP.NET MVC @ViewData["Version"] on @ViewData["Runtime"]!</h2>

myPro/Views/Shared/PV.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

<span>@TempData["Hello"]</span>
@model String
<b id="view" onclick="">@Model "ClickMe"</b>

<script>
$("#view").on("click", function() {
  alert('Hello world!');
});
</script>

myPro/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.title</title>
</head>
<body>
	@RenderBody()
	@Html.ActionLink("TestControl", "Index", "Test")
	@*Html.ActionLink("ViewResult", "VR", "PV", new { id=1 })*@
	@*建議這樣寫*@
	<div>RenderPartial:[
	  @{
		Html.RenderPartial("PV", ViewData);
	  }
	]</div>
	<div>RenderAction:[
		@*Html.RenderAction("MenuView", "PV")*@
	]</div>
</body>
</html>

myPro/Views/Test/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.title</title>
</head>
<body>
	@ViewBag.test
</body>
</html>
